image:
  file: .docker/gitpod/Dockerfile

additionalRepositories:
 - url: https://github.com/leanprover-community/mathlib4

vscode:
  extensions:
    - leanprover.lean4

tasks:
  - init: |
      elan self update
      cd ../mathlib4
      git checkout v4.18.0
      lake exe cache get
